### ISSUE TITLE
[Bug]: Do not build on macOS15 - Remove macOS 15 support

### ISSUE THREAD

**Issue by krzyzanowskim** [apple/container#169]
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

As of today the project does not build on macOS 15.

```
 error: cannot find type 'vmnet_network_ref' in scope
 49 |         var macAddress: String?
 50 |         #if !CURRENT_SDK
 51 |         var reference: vmnet_network_ref
    |                        `- error: cannot find type 'vmnet_network_ref' in scope
 52 |         #endif
 53 |     } 
```

Given the stance about no support of macOS 15, 
> the container maintainers typically will not address issues discovered on macOS 15 that cannot be reproduced on the macOS 26 Beta 1.

I find it odd the Package.swift specify .macOS("15") version. 

https://github.com/apple/container/blob/97d4ed6705a81ad4f8ec650b01aee2ef7504a3bc/Package.swift#L38

### Current behavior

As of today the project does not build on macOS 15.

```
 error: cannot find type 'vmnet_network_ref' in scope
 49 |         var macAddress: String?
 50 |         #if !CURRENT_SDK
 51 |         var reference: vmnet_network_ref
    |                        `- error: cannot find type 'vmnet_network_ref' in scope
 52 |         #endif
 53 |     } 
```

### Expected Behavior

No macOS 15 support whatsoever

### Environment

```markdown
- OS: macOS 15.5
- swift: 
- xcode: 
- container:
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by heywoodlh** [comment]
It does build on MacOS 15 (I built it on MacOS 15.5 today). You need XCode 26 beta as stated in the README:

https://github.com/apple/container/blob/7ca5a4313ff2bc22bb39ad2dd0848ad947953f54/BUILDING.md?plain=1#L3-L6

Once XCode 26 beta is installed, switch to it as your active XCode:

```
sudo xcode-select -s /Applications/Xcode-beta.app/
```

(You'll need to launch XCode-beta and accept the license agreement -- or use the command that is suggested to accept the license when you try to run XCode things)

**Comment by katiewasnothere** [comment]
Thanks for the report! Closing as @heywoodlh 's response should resolve the issue. If the issue is not resolved, please open a new issue including the version of Xcode you're using and the command you're using to build.
